version: '3'
services:
  myservice:
    hostname: myservice
    container_name: myservice
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./:/myservice
